### ISSUE TITLE
Update of csv files

### ISSUE THREAD

**Issue by YHHuan** [RohanPankaj/NBA-Prediction#20]
Hello, I'm wondering if there'll be a update of csv file or a better recommendation to combine newer data and keep up with new stuff

**Comment by RohanPankaj** [comment]
The [Save CSVs.ipynb](https://github.com/RohanPankaj/NBA-Prediction/blob/master/Save%20CSVs.ipynb) program already pulls data from all games since 2009, including any games played this season.
